// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit, Inter } from "next/font/google";
import { Suspense } from "react";

import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "DealIn",
  description: "Generated by create next app",

  icons: {
    icon: "/favicon_io/favicon-32x32.png", // browser tab
    shortcut: "/favicon_io/favicon-16x16.png",
    apple: "/favicon_io/apple-touch-icon.png",
  },

  openGraph: {
    title: "DealIn",
    description:
      "India’s trusted Bitumen B2B platform for sellers and brokers.",
    url: "https://dealin.netlify.app/",
    siteName: "DealIn",
    images: [
      {
        url: "/Images/DEALIN.svg",
        width: 1200,
        height: 630,
        alt: "DealIn WhatsApp Preview",
      },
      {
        url: "/Images/DEALIN.svg",
        width: 1080,
        height: 1080,
        alt: "DealIn Instagram Preview",
      },
    ],
    locale: "en_IN",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "DealIn",
    description:
      "Join India's digital Bitumen marketplace for brokers and sellers.",
    images: ["/Images/DEALIN.svg"],
    creator: "@dealinofficial", // optional
  },

  metadataBase: new URL("https://dealin.netlify.app"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` antialiased ${outfit.variable} ${inter.variable}`}>
        <Suspense fallback={null}>{children}</Suspense>
      </body>
    </html>
  );
}
